import { readdirSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import stylex from '@stylexjs/unplugin';

// Multi-page rather than a router: real files at real paths, which GitHub Pages
// serves without a 404 fallback, and each page ships only its own bundle.
// Generated by scripts/gen-pages.mjs, so adding a package adds a page.
function pageInputs() {
  const root = resolve(__dirname);
  const inputs: Record<string, string> = { main: resolve(root, 'index.html') };
  for (const name of readdirSync(root, { withFileTypes: true })) {
    if (!name.isDirectory()) continue;
    if (['src', 'dist', 'node_modules', 'scripts', 'public'].includes(name.name))
      continue;
    const html = resolve(root, name.name, 'index.html');
    if (existsSync(html)) inputs[name.name] = html;
  }
  return inputs;
}

export default defineConfig({
  // GitHub project pages serve from /<repo>/, not the domain root. CI sets
  // BASE_PATH; local builds and dev stay at the root.
  base: process.env.BASE_PATH ?? '/',
  plugins: [stylex.vite(), react()],
  build: { rollupOptions: { input: pageInputs() } },
});
